# Generated by Django 5.1.1 on 2024-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_flower_stock'),
        ('orders', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(to='catalog.flower'),
        ),
    ]
