# Generated by Django 5.1.1 on 2024-11-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_flower_is_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='is_on_sale',
        ),
    ]
